### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'accounts'

### ISSUE THREAD

**Issue by taiduu** [ayushteke/slam_aria_mirror_bot_HEROKU#8]
Hi 

I have deployed as instructed but I am getting this service accounts error.

```
2021-08-03T08:26:12.702613+00:00 heroku[worker.1]: Starting process with command `/bin/sh -c bash\ start.sh`
2021-08-03T08:26:13.503535+00:00 heroku[worker.1]: State changed from starting to up
2021-08-03T08:26:20.508054+00:00 app[worker.1]: 2021-08-03 08:26:20,507 - bot - INFO - Generating USER_SESSION_STRING
2021-08-03T08:26:20.510367+00:00 app[worker.1]: 2021-08-03 08:26:20,510 - bot - INFO - Generating TELEGRAPH_TOKEN using 'PACdYgds' name
2021-08-03T08:26:20.843022+00:00 app[worker.1]: 2021-08-03 08:26:20,827 - root - INFO - UPTOBOX_TOKEN not provided!
2021-08-03T08:26:22.373876+00:00 app[worker.1]: Traceback (most recent call last):
2021-08-03T08:26:22.373899+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2021-08-03T08:26:22.374178+00:00 app[worker.1]:     return _run_code(code, main_globals, None,
2021-08-03T08:26:22.374211+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
2021-08-03T08:26:22.374395+00:00 app[worker.1]:     exec(code, run_globals)
2021-08-03T08:26:22.374426+00:00 app[worker.1]:   File "/usr/src/app/bot/__main__.py", line 21, in <module>
2021-08-03T08:26:22.374650+00:00 app[worker.1]:     from .modules import authorize, list, cancel_mirror, mirror_status, mirror, clone, watch, shell, eval, search, delete, speedtest, usage, mediainfo, count, config, updates
2021-08-03T08:26:22.374681+00:00 app[worker.1]:   File "/usr/src/app/bot/modules/list.py", line 2, in <module>
2021-08-03T08:26:22.374818+00:00 app[worker.1]:     from bot.helper.mirror_utils.upload_utils.gdriveTools import GoogleDriveHelper
2021-08-03T08:26:22.374857+00:00 app[worker.1]:   File "/usr/src/app/bot/helper/mirror_utils/upload_utils/gdriveTools.py", line 32, in <module>
2021-08-03T08:26:22.375028+00:00 app[worker.1]:     SERVICE_ACCOUNT_INDEX = randrange(len(os.listdir("accounts")))
2021-08-03T08:26:22.375071+00:00 app[worker.1]: FileNotFoundError: [Errno 2] No such file or directory: 'accounts'
2021-08-03T08:26:22.737222+00:00 heroku[worker.1]: Process exited with status 1
2021-08-03T08:26:22.843198+00:00 heroku[worker.1]: State changed from up to crashed
```

**Comment by dinesh-0602** [comment]
Zip the 100 json files only not folder. Or your ACCOUNTS_ZIP_URL is not a direct link or the link has any problem for sure
